# Generated by Django 3.2.9 on 2021-11-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
