# Generated by Django 3.2.9 on 2021-11-03 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereportstudent',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='LeaveReportStaff',
        ),
        migrations.DeleteModel(
            name='LeaveReportStudent',
        ),
    ]
