# Generated by Django 3.2.9 on 2021-11-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0002_alter_students_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
