# Generated by Django 3.2.9 on 2021-12-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0002_auto_20211202_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecipt',
            name='student_name',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
