# Generated by Django 3.2.9 on 2021-12-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0003_studentrecipt_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecipt',
            name='student_id',
        ),
    ]
