# Generated by Django 3.2.9 on 2021-12-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0004_remove_studentrecipt_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecipt',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
